from binary_search_tree.bst import BST

tree = BST()
tree.insert(9)
tree.insert(4)
tree.insert(6)
tree.insert(20)
tree.insert(170)
tree.insert(15)
tree.insert(1)
tree.insert(0)
tree.insert(2)
tree.insert(5)
tree.insert(7)
tree.insert(14)
tree.insert(16)
tree.insert(169)
tree.insert(171)
tree.insert(3)
print(tree.lookup(172))
print(tree.breadth_first_search())
print(tree.depth_first_search(traversal="post_order"))
